// Auto-generated by scripts/generate-env.js
window.__ENV = {
  "DEEPSEEK_BASE_URL": "http://localhost:5000",
  "NGROK_SKIP_BROWSER_WARNING": "1",
  "DEEPSEEK_API_KEY": "sk-5ba061fb9c3242baa0d6c72d915bc56d"
};
