const fs = require('fs');
const path = require('path');
const dotenv = require('dotenv');

const envPath = path.resolve(__dirname, '..', '.env');
const outPath = path.resolve(__dirname, '..', 'env-config.js');

if (!fs.existsSync(envPath)) {
  console.error('.env not found at', envPath);
  process.exit(1);
}

const env = dotenv.parse(fs.readFileSync(envPath));

const config = {
  DEEPSEEK_BASE_URL: env.DEEPSEEK_BASE_URL || '',
  NGROK_SKIP_BROWSER_WARNING: env.NGROK_SKIP_BROWSER_WARNING || '0',
  DEEPSEEK_API_KEY: env.DEEPSEEK_API_KEY || ''
};

const content = `// Auto-generated by scripts/generate-env.js
window.__ENV = ${JSON.stringify(config, null, 2)};
`;

fs.writeFileSync(outPath, content, { encoding: 'utf8' });
console.log('Wrote', outPath);
